const ACTION_TYPES = {

	//user login action keys 
	USER_NAME_CHANGED: 'USER_NAME',
	PASSWORD_CHANGED: 'PASSWORD_CHANGED',
	SIGNUP_USER_RES: 'SIGNUP_USER_RES',
	FETCHING_DATA: 'FETCHING_DATA',
    RESET_DATA: 'RESET_DATA',
    
    FIRST_NAME_CHANGED:'FIRST_NAME_CHANGED',
    LAST_NAME_CHANGED:'LAST_NAME_CHANGED',
    EMAIL_CHANGED:'EMAIL_CHANGED',
    PASSWORD_CHANGED:'PASSWORD_CHANGED',
    CLEAR_RESPONSE:'CLEAR_RESPONSE',
    FETCH_SIGNUP_RESPONSE_DATA:'FETCH_SIGNUP_RESPONSE_DATA',
    SERVICE_PREF_RES:'SERVICE_PREF_RES'
	

}

export default ACTION_TYPES
